// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ1TZTsoDbm6P-f6SqjO9cKBhGZl3dFVk',
    appId: '1:943810789025:web:fc1dfc47822b70b2097ae0',
    messagingSenderId: '943810789025',
    projectId: 'auth-cycle-project',
    authDomain: 'auth-cycle-project.firebaseapp.com',
    storageBucket: 'auth-cycle-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7_zq_wO8YScTVjVGs14meBXldB6Gqu5Q',
    appId: '1:943810789025:android:8b36637cd6e64fce097ae0',
    messagingSenderId: '943810789025',
    projectId: 'auth-cycle-project',
    storageBucket: 'auth-cycle-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCdp6Qerz1ewNaFLH3AqROLYDr_F48BHw',
    appId: '1:943810789025:ios:2807d27bd536fc53097ae0',
    messagingSenderId: '943810789025',
    projectId: 'auth-cycle-project',
    storageBucket: 'auth-cycle-project.firebasestorage.app',
    iosBundleId: 'com.example.authscreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCdp6Qerz1ewNaFLH3AqROLYDr_F48BHw',
    appId: '1:943810789025:ios:2807d27bd536fc53097ae0',
    messagingSenderId: '943810789025',
    projectId: 'auth-cycle-project',
    storageBucket: 'auth-cycle-project.firebasestorage.app',
    iosBundleId: 'com.example.authscreen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ1TZTsoDbm6P-f6SqjO9cKBhGZl3dFVk',
    appId: '1:943810789025:web:347376b41e88a53a097ae0',
    messagingSenderId: '943810789025',
    projectId: 'auth-cycle-project',
    authDomain: 'auth-cycle-project.firebaseapp.com',
    storageBucket: 'auth-cycle-project.firebasestorage.app',
  );
}
